### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by swpknl** [omaha-consulting/omaha-server#367]
Hi Team,
I have setup the Omaha server on my local machine. I have also customized the Omaha client to remove the branding, but I am getting 400 bad request. Could you please tell from the logs what could lead to the error?
Please let me know if you need any further details.

Regards,
Swapnil
[Omaha log.txt](https://github.com/omaha-consulting/omaha-server/files/7186146/Omaha.log.txt)

**Comment by mherrmann** [comment]
Hi, the open source version of omaha-server you see here is not compatible with the latest Omaha clients. For the latest fixes, you need to obtain the Python 3 version of our server. Please see our [Pricing page](https://omaha-consulting.com/pricing) for details.

**Comment by swpknl** [comment]
Ok, thank you.
